export const CONNECTED = 'CONNECTED'
export const SET_PAGE_STATE = 'SET_PAGE_STATE'
export const GET_STATE = 'GET_STATE'
export const DISPATCH = 'DISPATCH'
export const SET_ITEM_STATE = 'SET_ITEM_STATE'
